import React, {useState, useEffect, useCallback, FC} from 'react';
import {View, Text} from 'react-native';

const TestScroll = () => {
  return (
    <View style={{justifyContent: 'center', alignItems: 'center'}}>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
      <View>
        <Text>aaaaa</Text>
      </View>
    </View>
  );
};

export default TestScroll;
